name: WISE Hotfix
description: File a WISE hotifx
title: "[WISE Hotfix]: "
labels: ["hotfix", "W.I.S.E."]
assignees:
  - spydmobile
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this hotfix report! By submitting this issue, you agree to follow our [Code of Conduct](https://firegrowthmodel.ca/pages/conduct.html)
  - type: input
    id: contact
    attributes:
      label: Contact Details - Who is fixing this
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
  - type: textarea
    id: why-does-it-matter
    attributes:
      label: Why is this happening?
      description: Tell us why this is necessary
      placeholder: Why?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: approval
    attributes:
      label: Approvals Process
      description: All to be completed for bug fix
      options:
        - label: Pull Request 
        - label: Merge
      
    
